package com.mycompany.carrental.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DrivingLicenseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDrivingLicenseAllPropertiesEquals(DrivingLicense expected, DrivingLicense actual) {
        assertDrivingLicenseAutoGeneratedPropertiesEquals(expected, actual);
        assertDrivingLicenseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDrivingLicenseAllUpdatablePropertiesEquals(DrivingLicense expected, DrivingLicense actual) {
        assertDrivingLicenseUpdatableFieldsEquals(expected, actual);
        assertDrivingLicenseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDrivingLicenseAutoGeneratedPropertiesEquals(DrivingLicense expected, DrivingLicense actual) {
        assertThat(actual)
            .as("Verify DrivingLicense auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDrivingLicenseUpdatableFieldsEquals(DrivingLicense expected, DrivingLicense actual) {
        assertThat(actual)
            .as("Verify DrivingLicense relevant properties")
            .satisfies(a -> assertThat(a.getLicenseNumber()).as("check licenseNumber").isEqualTo(expected.getLicenseNumber()))
            .satisfies(a -> assertThat(a.getIssueDate()).as("check issueDate").isEqualTo(expected.getIssueDate()))
            .satisfies(a -> assertThat(a.getExpirationDate()).as("check expirationDate").isEqualTo(expected.getExpirationDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDrivingLicenseUpdatableRelationshipsEquals(DrivingLicense expected, DrivingLicense actual) {
        // empty method
    }
}
